/**
 * Campos Agua y Saneamiento — solo bases Maqueta + Bitácora oficiales.
 * Capas v5: alta + tablas actualizables (sin mezclar otros temas).
 */
import type { FormField } from "../shared";
import { applyAguaSelectOptions } from "./select-options";

/** Capas oficiales (duplicado local para evitar ciclo de imports con capture-forms). */
const CAPA_OPTIONS = [
  "Alta / orden",
  "Variables líder",
  "Modificación contractual",
  "Bitácora estado",
  "Bitácora estructuración",
  "Pago / desembolso",
  "CDPS y RC",
  "Control ejecución física",
];

const RAW_FIELDS: FormField[] = [
  { name: "tipo_registro", label: "Tipo de registro", type: "select", required: true, options: CAPA_OPTIONS, excelWidth: 24 },
  { name: "capa", label: "Formulario", type: "select", required: true, options: CAPA_OPTIONS, excelWidth: 22 },
  { name: "clave_seguimiento", label: "Identificador (orden de proveeduría)", type: "text", excelWidth: 28 },
  { name: "orden_de_proveeduria", label: "Orden de proveeduría", type: "text", excelWidth: 22 },
  { name: "orden_de_proveeduria_segmentado", label: "Orden segmentada", type: "text", excelWidth: 28 },
  { name: "op2", label: "Orden relacionada", type: "text", excelWidth: 18 },
  { name: "nit", label: "NIT del proveedor", type: "text", excelWidth: 18 },
  { name: "proveedor", label: "Proveedor", type: "text", excelWidth: 18 },
  { name: "valor", label: "Valor de la orden", type: "number", excelWidth: 18 },
  { name: "vigencia", label: "Vigencia", type: "text", excelWidth: 18 },
  { name: "tipo_de_orden", label: "Tipo de orden", type: "text", excelWidth: 18 },
  { name: "orden_relacionada_control_y_seg", label: "Orden relacionada (control y seguimiento)", type: "text", excelWidth: 28 },
  { name: "proveedor_o_p_par", label: "Proveedor (orden parcial)", type: "text", excelWidth: 18 },
  { name: "region", label: "Región", type: "text", excelWidth: 18 },
  { name: "provincia", label: "Provincia", type: "text", excelWidth: 18 },
  { name: "departamento", label: "Departamento", type: "text", excelWidth: 18 },
  { name: "municipio", label: "Municipio", type: "text", excelWidth: 18 },
  { name: "fecha", label: "Fecha de suscripción", type: "date", excelWidth: 18 },
  { name: "objeto", label: "Objeto del contrato / orden", type: "textarea", excelWidth: 18 },
  { name: "decreto", label: "Decreto", type: "text", excelWidth: 18 },
  { name: "tipo_maquina", label: "Tipo de máquina", type: "text", excelWidth: 18 },
  // Solo import Excel/legacy. En captura UI no se muestra: el geo es territorial
  // (departamento/municipio DIVIPOLA), no coordenadas de punto.
  { name: "coordenadas", label: "Coordenadas (solo Excel; en captura use departamento/municipio)", type: "text", excelWidth: 18 },
  { name: "plazo_de_ejecucion_dias", label: "Plazo de ejecución (días)", type: "number", excelWidth: 18 },
  { name: "forma_de_pago", label: "Forma de pago", type: "text", excelWidth: 18 },
  { name: "n_sigob_de_solicitud", label: "Número SIGOB de solicitud", type: "text", excelWidth: 18 },
  { name: "n_sigob_de_respuesta", label: "Número SIGOB de respuesta", type: "text", excelWidth: 18 },
  { name: "tipo_de_evento", label: "Tipo de evento", type: "text", excelWidth: 18 },
  { name: "administracion", label: "Administración", type: "text", excelWidth: 18 },
  { name: "procesos_juridicos", label: "Procesos jurídicos", type: "text", excelWidth: 18 },
  { name: "nombre_orden", label: "Nombre de la orden", type: "text", excelWidth: 18 },
  { name: "categorizacion", label: "Categorización", type: "text", excelWidth: 18 },
  { name: "no_cdp", label: "Número de CDP", type: "text", excelWidth: 18 },
  { name: "n_cdp", label: "Número de CDP (alterno)", type: "text", excelWidth: 18 },
  { name: "fecha_cdp", label: "Fecha del CDP", type: "date", excelWidth: 18 },
  { name: "valor_cdp", label: "Valor del CDP", type: "number", excelWidth: 18 },
  { name: "no_rc", label: "Número de RC", type: "text", excelWidth: 18 },
  { name: "n_rc", label: "Número de RC (alterno)", type: "text", excelWidth: 18 },
  { name: "fecha_rc", label: "Fecha del RC", type: "date", excelWidth: 18 },
  { name: "valor_rc", label: "Valor del RC", type: "number", excelWidth: 18 },
  { name: "expediente", label: "Expediente", type: "text", excelWidth: 18 },
  { name: "responsable_apoyo_a_la_supervision", label: "Responsable de apoyo a la supervisión", type: "text", excelWidth: 28 },
  { name: "fecha_de_asignacion", label: "Fecha de asignación", type: "date", excelWidth: 18 },
  { name: "estado", label: "Estado", type: "text", excelWidth: 22 },
  { name: "estado_de_ejecucion", label: "Estado de ejecución", type: "text", excelWidth: 22 },
  { name: "fecha_inicio_orden", label: "Fecha de inicio de la orden", type: "date", excelWidth: 18 },
  { name: "fecha_fin_orden", label: "Fecha de fin de la orden", type: "date", excelWidth: 18 },
  { name: "ejecucion", label: "Porcentaje de ejecución", type: "number", excelWidth: 18 },
  { name: "fecha_radicacion_expediente", label: "Fecha de radicación del expediente", type: "date", excelWidth: 28 },
  { name: "tecnico_asignado", label: "Técnico asignado", type: "text", excelWidth: 18 },
  { name: "abogado_asignado_r_tecnica", label: "Abogado asignado (revisión técnica)", type: "text", excelWidth: 28 },
  { name: "financiero_asignado", label: "Financiero asignado", type: "text", excelWidth: 18 },
  { name: "fecha_de_aval", label: "Fecha de aval", type: "date", excelWidth: 18 },
  { name: "cantidad_reiteraciones", label: "Cantidad de reiteraciones", type: "number", excelWidth: 18 },
  { name: "cantidad_observaciones", label: "Cantidad de observaciones", type: "number", excelWidth: 18 },
  { name: "dias_en_tecnico", label: "Días en técnico", type: "number", excelWidth: 18 },
  { name: "dias_en_proveedor", label: "Días en proveedor", type: "number", excelWidth: 18 },
  { name: "dias_contractual", label: "Días en área contractual", type: "number", excelWidth: 18 },
  { name: "dias_financiera", label: "Días en área financiera", type: "number", excelWidth: 18 },
  { name: "dias_subdirector", label: "Días en subdirección", type: "number", excelWidth: 18 },
  { name: "dias_subdireccion_general", label: "Días en subdirección general", type: "number", excelWidth: 28 },
  { name: "dias_gafc", label: "Días en GAFC", type: "number", excelWidth: 18 },
  { name: "dias_fiduprevisora", label: "Días en Fiduprevisora", type: "number", excelWidth: 18 },
  { name: "dias_totales_en_la_linea", label: "Días totales en la línea", type: "number", excelWidth: 18 },
  { name: "dias_en_gestion_de_pagos", label: "Días en gestión de pagos", type: "number", excelWidth: 18 },
  { name: "n_ratificacion", label: "Número de ratificación", type: "text", excelWidth: 18 },
  { name: "sd", label: "Solicitud de desembolso (SD)", type: "text", excelWidth: 18 },
  { name: "valor_pagado", label: "Valor pagado", type: "number", excelWidth: 18 },
  { name: "comprobante_de_egreso", label: "Comprobante de egreso", type: "text", excelWidth: 18 },
  { name: "voucher", label: "Voucher / comprobante", type: "text", excelWidth: 18 },
  { name: "fecha_de_pago", label: "Fecha de pago", type: "date", excelWidth: 18 },
  { name: "op_paga", label: "Orden pagada", type: "text", excelWidth: 18 },
  { name: "etapa", label: "Etapa", type: "text", excelWidth: 18 },
  { name: "estado_actual", label: "Estado actual", type: "text", excelWidth: 18 },
  { name: "proceso_actual", label: "Proceso actual", type: "text", excelWidth: 18 },
  { name: "dependencia", label: "Dependencia", type: "text", excelWidth: 18 },
  { name: "dias_desde_ult_gestion", label: "Días desde la última gestión", type: "number", excelWidth: 18 },
  { name: "fecha_ultimo_seguimiento", label: "Fecha del último seguimiento", type: "date", excelWidth: 18 },
  { name: "comentario_ult_seguimiento_a_supervision", label: "Comentario del último seguimiento (supervisión)", type: "textarea", excelWidth: 28 },
  { name: "novedades", label: "Novedades", type: "textarea", excelWidth: 18 },
  { name: "validaciom", label: "Validación", type: "text", excelWidth: 18 },
  { name: "cntd_tanques_de_almacenamiento_de_agua_contratados", label: "Tanques de agua contratados (cantidad)", type: "text", excelWidth: 28 },
  { name: "capacidad_lts_tanques_contratados", label: "Capacidad de tanques contratados (litros)", type: "number", excelWidth: 28 },
  { name: "cantidad_carrotanques_contratadas", label: "Carrotanques contratados (cantidad)", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_crrt_contratadas", label: "Capacidad de carrotanques contratados (litros)", type: "number", excelWidth: 28 },
  { name: "dias_suministro_crrt_contratada", label: "Días de suministro contratados (carrotanque)", type: "number", excelWidth: 28 },
  { name: "cntd_vactor_contratadas", label: "Vactors contratados (cantidad)", type: "text", excelWidth: 18 },
  { name: "capacidad_lt_vactor_contratada", label: "Capacidad de vactors contratados (litros)", type: "number", excelWidth: 28 },
  { name: "dias_suministro_vactor_contratada", label: "Días de suministro contratados (vactor)", type: "number", excelWidth: 28 },
  { name: "cantidad_maquinas_m_a_contratadas", label: "Máquinas (obra) contratadas (cantidad)", type: "number", excelWidth: 28 },
  { name: "horas_maquina_m_a", label: "Horas máquina contratadas", type: "number", excelWidth: 18 },
  { name: "dias_volqueta_m_a_contratadas", label: "Días de volqueta contratados", type: "number", excelWidth: 28 },
  { name: "cantidad_de_tanques_de_almacenamiento_de_agua_ejecutadas", label: "Tanques de agua ejecutados (cantidad)", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_tanques_ejecutados", label: "Capacidad de tanques ejecutados (litros)", type: "number", excelWidth: 28 },
  { name: "cantidad_carrotanques_ejecutadas", label: "Carrotanques ejecutados (cantidad)", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_2_crrt", label: "Capacidad de carrotanques ejecutados (litros)", type: "number", excelWidth: 18 },
  { name: "dias_suministro_crrt", label: "Días de suministro ejecutados (carrotanque)", type: "number", excelWidth: 18 },
  { name: "cntd_vactor_ejecutadas", label: "Vactors ejecutados (cantidad)", type: "text", excelWidth: 18 },
  { name: "capacidad_lt_vactor_ejecutadas", label: "Capacidad de vactors ejecutados (litros)", type: "number", excelWidth: 28 },
  { name: "dias_suministro_vactor_ejecutadas", label: "Días de suministro ejecutados (vactor)", type: "number", excelWidth: 28 },
  { name: "cantidad_maquinas_m_a_ejecutadas", label: "Máquinas (obra) ejecutadas (cantidad)", type: "number", excelWidth: 28 },
  { name: "horas_maquina_m_a_ejecutadas", label: "Horas máquina ejecutadas", type: "number", excelWidth: 28 },
  { name: "dias_volqueta_m_a_ejecutadas", label: "Días de volqueta ejecutados", type: "number", excelWidth: 28 },
  { name: "num_modificacion", label: "Número de modificación", type: "text", excelWidth: 18 },
  { name: "tipo_de_modificacion", label: "Tipo de modificación", type: "text", excelWidth: 18 },
  { name: "modificacion", label: "Descripción de la modificación", type: "text", excelWidth: 22 },
  { name: "horas_maquina", label: "Horas máquina", type: "number", excelWidth: 18 },
  { name: "dias_volqueta", label: "Días de volqueta", type: "number", excelWidth: 18 },
  { name: "sin_info", label: "Sin información", type: "text", excelWidth: 18 },
  { name: "valor_parcial_1", label: "Valor parcial 1", type: "number", excelWidth: 18 },
  { name: "valor_parcial_2", label: "Valor parcial 2", type: "number", excelWidth: 18 },
  { name: "valor_parcial_3", label: "Valor parcial 3", type: "number", excelWidth: 18 },
  /** Label Excel real; «obs» queda como alias en remap (template.ts). */
  { name: "observaciones", label: "Observaciones", type: "textarea", excelWidth: 18 },
  { name: "horas", label: "Horas", type: "number", excelWidth: 18 },
  { name: "verif", label: "Verificación", type: "text", excelWidth: 18 },
  { name: "fecha_estado", label: "Fecha del estado", type: "date", excelWidth: 18 },
  { name: "estado_macro", label: "Estado general", type: "text", excelWidth: 18 },
  { name: "semana_seguimiento", label: "Semana de seguimiento", type: "text", excelWidth: 18 },
  { name: "comentario_semanal", label: "Comentario semanal", type: "textarea", excelWidth: 28 },
  { name: "orden_de_proveeduria_x_pago", label: "Orden de proveeduría por pago", type: "text", excelWidth: 28 },
  { name: "proceso", label: "Proceso", type: "text", excelWidth: 18 },
  { name: "comentario", label: "Comentario", type: "textarea", excelWidth: 18 },
  { name: "valor_op_parcial", label: "Valor de la orden (parcial)", type: "number", excelWidth: 18 },
  { name: "ano", label: "Año", type: "text", excelWidth: 18 },
  { name: "n_contrato", label: "Número de contrato", type: "text", excelWidth: 18 },
  { name: "sd_solicitud_de_desembolso", label: "Solicitud de desembolso", type: "text", excelWidth: 28 },
  { name: "valor_pagado_sin_impuestos", label: "Valor pagado (sin impuestos)", type: "number", excelWidth: 28 },
  { name: "valor_pagado_total_con_impuestos", label: "Valor pagado (con impuestos)", type: "number", excelWidth: 28 },
  // Calculado en captura Pagos: valor_op_parcial − valor_pagado_total_con_impuestos
  { name: "saldo_a_liberar", label: "Saldo a liberar", type: "number", excelWidth: 18 },
  // Alias legacy Excel — no mostrar en captura (ver capture-forms pagos)
  { name: "saldo_por_liberar", label: "Saldo por liberar", type: "number", excelWidth: 18 },
  { name: "comentario_depuracion", label: "Comentario de depuración", type: "textarea", excelWidth: 18 },
  // Columna Excel legacy mal escrita — no mostrar en captura
  { name: "odern_3", label: "Orden adicional (Excel)", type: "text", excelWidth: 18 },
];

export const SCHEMA_VERSION = 7;

export const SOURCE_FIELDS: FormField[] =
  applyAguaSelectOptions(RAW_FIELDS) as FormField[];
