/**
 * Campos generados desde fuentes reales (maqueta / bitácora / ArcGIS).
 * NO editar a mano — regenerar: node scripts/generate-theme-fields.cjs
 * Fuente: General+control+modificaciones+bitacora+PAGOS
 * schemaVersion 3: capas + clave_seguimiento para cruces y seguimiento.
 */
import type { FormField } from "../shared";

export const SOURCE_FIELDS: FormField[] = [
  { name: "tipo_registro", label: "Tipo de registro", type: "select", required: true, options: ["Maqueta / orden","Control ejecución física","Modificación contractual","Bitácora estado","Pago / desembolso"], excelWidth: 24 },
  { name: "capa", label: "Capa (Maqueta / Bitácora / …)", type: "select", required: true, options: ["Maqueta / orden","Control ejecución física","Modificación contractual","Bitácora estado","Pago / desembolso"], excelWidth: 22 },
  { name: "clave_seguimiento", label: "Clave de seguimiento (Orden de proveeduría)", type: "text", excelWidth: 28 },
  { name: "orden_de_proveeduria", label: "Orden de proveeduría", type: "text", excelWidth: 22 },
  { name: "orden_de_proveeduria_segmentado", label: "Orden de proveeduría-Segmentado", type: "text", excelWidth: 28 },
  { name: "op2", label: "OP2", type: "text", excelWidth: 18 },
  { name: "nit", label: "Nit", type: "text", excelWidth: 18 },
  { name: "proveedor", label: "Proveedor", type: "text", excelWidth: 18 },
  { name: "valor", label: "ValorOP", type: "number", excelWidth: 18 },
  { name: "vigencia", label: "Vigencia", type: "text", excelWidth: 18 },
  { name: "tipo_de_orden", label: "Tipo de orden", type: "text", excelWidth: 18 },
  { name: "orden_relacionada_control_y_seg", label: "Orden relacionada- control y seg", type: "text", excelWidth: 28 },
  { name: "proveedor_o_p_par", label: "Proveedor O.P PAR", type: "text", excelWidth: 18 },
  { name: "region", label: "Región", type: "text", excelWidth: 18 },
  { name: "provincia", label: "Provincia", type: "text", excelWidth: 18 },
  { name: "departamento", label: "Departamento", type: "text", excelWidth: 18 },
  { name: "municipio", label: "Municipio", type: "text", excelWidth: 18 },
  { name: "fecha", label: "Fecha sucripcion", type: "date", excelWidth: 18 },
  { name: "objeto", label: "Objeto", type: "textarea", excelWidth: 18 },
  { name: "decreto", label: "Decreto", type: "text", excelWidth: 18 },
  { name: "tipo_maquina", label: "tipo maquina", type: "text", excelWidth: 18 },
  { name: "coordenadas", label: "Coordenadas", type: "text", excelWidth: 18 },
  { name: "plazo_de_ejecucion_dias", label: "Plazo de Ejecución Dias", type: "number", excelWidth: 18 },
  { name: "forma_de_pago", label: "Forma de Pago", type: "text", excelWidth: 18 },
  { name: "n_sigob_de_solicitud", label: "N° Sigob de solicitud", type: "text", excelWidth: 18 },
  { name: "n_sigob_de_respuesta", label: "N° Sigob de respuesta", type: "text", excelWidth: 18 },
  { name: "tipo_de_evento", label: "Tipo de Evento", type: "text", excelWidth: 18 },
  { name: "administracion", label: "Administración", type: "text", excelWidth: 18 },
  { name: "procesos_juridicos", label: "Procesos Juridicos", type: "text", excelWidth: 18 },
  { name: "nombre_orden", label: "Nombre orden", type: "text", excelWidth: 18 },
  { name: "categorizacion", label: "Categorización", type: "text", excelWidth: 18 },
  { name: "no_cdp", label: "CDP", type: "text", excelWidth: 18 },
  { name: "n_cdp", label: "N° CDP", type: "text", excelWidth: 18 },
  { name: "fecha_cdp", label: "Fecha CDP", type: "date", excelWidth: 18 },
  { name: "valor_cdp", label: "Valor CDP", type: "number", excelWidth: 18 },
  { name: "no_rc", label: "RC", type: "text", excelWidth: 18 },
  { name: "n_rc", label: "N° RC", type: "text", excelWidth: 18 },
  { name: "fecha_rc", label: "Fecha RC", type: "date", excelWidth: 18 },
  { name: "valor_rc", label: "Valor RC", type: "number", excelWidth: 18 },
  { name: "expediente", label: "Expediente", type: "text", excelWidth: 18 },
  { name: "responsable_apoyo_a_la_supervision", label: "Responsable Apoyo a la supervisión", type: "text", excelWidth: 28 },
  { name: "fecha_de_asignacion", label: "Fecha de asignación", type: "date", excelWidth: 18 },
  { name: "estado", label: "Estado de ejecución", type: "text", excelWidth: 18 },
  { name: "fecha_inicio_orden", label: "Fecha Inicio Orden", type: "date", excelWidth: 18 },
  { name: "fecha_fin_orden", label: "Fecha fin Orden", type: "date", excelWidth: 18 },
  { name: "ejecucion", label: "% Ejecución", type: "number", excelWidth: 18 },
  { name: "fecha_radicacion_expediente", label: "Fecha radicacion expediente", type: "date", excelWidth: 28 },
  { name: "tecnico_asignado", label: "Técnico asignado", type: "text", excelWidth: 18 },
  { name: "abogado_asignado_r_tecnica", label: "Abogado Asignado - R. Tecnica", type: "text", excelWidth: 28 },
  { name: "financiero_asignado", label: "Financiero Asignado", type: "text", excelWidth: 18 },
  { name: "fecha_de_aval", label: "Fecha de aval", type: "date", excelWidth: 18 },
  { name: "cantidad_reiteraciones", label: "Cantidad reiteraciones", type: "number", excelWidth: 18 },
  { name: "cantidad_observaciones", label: "Cantidad Observaciones", type: "number", excelWidth: 18 },
  { name: "dias_en_tecnico", label: "Días en Técnico", type: "number", excelWidth: 18 },
  { name: "dias_en_proveedor", label: "Días en Proveedor", type: "number", excelWidth: 18 },
  { name: "dias_contractual", label: "Días - Contractual", type: "number", excelWidth: 18 },
  { name: "dias_financiera", label: "Días - Financiera", type: "number", excelWidth: 18 },
  { name: "dias_subdirector", label: "Días - Subdirector", type: "number", excelWidth: 18 },
  { name: "dias_subdireccion_general", label: "Días - Subdirección General", type: "number", excelWidth: 28 },
  { name: "dias_gafc", label: "Días - GAFC", type: "number", excelWidth: 18 },
  { name: "dias_fiduprevisora", label: "Días - Fiduprevisora", type: "number", excelWidth: 18 },
  { name: "dias_totales_en_la_linea", label: "Dias totales en la linea", type: "number", excelWidth: 18 },
  { name: "dias_en_gestion_de_pagos", label: "Dias en Gestión de pagos", type: "number", excelWidth: 18 },
  { name: "n_ratificacion", label: "N° Ratificación", type: "text", excelWidth: 18 },
  { name: "sd", label: "SD", type: "text", excelWidth: 18 },
  { name: "valor_pagado", label: "Valor Pagado", type: "number", excelWidth: 18 },
  { name: "comprobante_de_egreso", label: "Comprobante de Egreso", type: "text", excelWidth: 18 },
  { name: "voucher", label: "Voucher", type: "text", excelWidth: 18 },
  { name: "fecha_de_pago", label: "Fecha de Pago", type: "date", excelWidth: 18 },
  { name: "op_paga", label: "OP Paga", type: "text", excelWidth: 18 },
  { name: "etapa", label: "Etapa", type: "text", excelWidth: 18 },
  { name: "estado_actual", label: "Estado Actual", type: "text", excelWidth: 18 },
  { name: "proceso_actual", label: "Proceso Actual", type: "text", excelWidth: 18 },
  { name: "dependencia", label: "Dependencia", type: "text", excelWidth: 18 },
  { name: "dias_desde_ult_gestion", label: "Días Desde Ult Gestión", type: "number", excelWidth: 18 },
  { name: "fecha_ultimo_seguimiento", label: "Fecha ultimo seguimiento", type: "date", excelWidth: 18 },
  { name: "comentario_ult_seguimiento_a_supervision", label: "Comentario Ult Seguimiento - A. Supervisión", type: "textarea", excelWidth: 28 },
  { name: "novedades", label: "Novedades", type: "textarea", excelWidth: 18 },
  { name: "validaciom", label: "validaciom", type: "text", excelWidth: 18 },
  { name: "cntd_tanques_de_almacenamiento_de_agua_contratados", label: "Cntd Tanques de almacenamiento de agua-CONTRATADOS", type: "text", excelWidth: 28 },
  { name: "capacidad_lts_tanques_contratados", label: "Capacidad LTS TANQUES -CONTRATADOS", type: "number", excelWidth: 28 },
  { name: "cantidad_carrotanques_contratadas", label: "Cantidad Carrotanques-CONTRATADAS", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_crrt_contratadas", label: "Capacidad LT CRRT - CONTRATADAS", type: "number", excelWidth: 28 },
  { name: "dias_suministro_crrt_contratada", label: "Dias Suministro CRRT-CONTRATADA", type: "number", excelWidth: 28 },
  { name: "cntd_vactor_contratadas", label: "Cntd  VACTOR-CONTRATADAS", type: "text", excelWidth: 18 },
  { name: "capacidad_lt_vactor_contratada", label: "Capacidad LT VACTOR - CONTRATADA", type: "number", excelWidth: 28 },
  { name: "dias_suministro_vactor_contratada", label: "Dias Suministro  VACTOR - CONTRATADA", type: "number", excelWidth: 28 },
  { name: "cantidad_maquinas_m_a_contratadas", label: "Cantidad Maquinas M.A-CONTRATADAS", type: "number", excelWidth: 28 },
  { name: "horas_maquina_m_a", label: "Horas Máquina M.A", type: "number", excelWidth: 18 },
  { name: "dias_volqueta_m_a_contratadas", label: "Días Volqueta M.A -CONTRATADAS", type: "number", excelWidth: 28 },
  { name: "cantidad_de_tanques_de_almacenamiento_de_agua_ejecutadas", label: "Cantidad de tanques de almacenamiento de agua-EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_tanques_ejecutados", label: "Capacidad LT TANQUES - EJECUTADOS", type: "number", excelWidth: 28 },
  { name: "cantidad_carrotanques_ejecutadas", label: "Cantidad Carrotanques-EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "capacidad_lt_2_crrt", label: "Capacidad LT 2 -CRRT", type: "number", excelWidth: 18 },
  { name: "dias_suministro_crrt", label: "Dias Suministro-CRRT", type: "number", excelWidth: 18 },
  { name: "cntd_vactor_ejecutadas", label: "Cntd  VACTOR-EJECUTADAS", type: "text", excelWidth: 18 },
  { name: "capacidad_lt_vactor_ejecutadas", label: "Capacidad LT VACTOR- Ejecutadas", type: "number", excelWidth: 28 },
  { name: "dias_suministro_vactor_ejecutadas", label: "Dias Suministro VACTOR - EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "cantidad_maquinas_m_a_ejecutadas", label: "Cantidad Maquinas M.A-EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "horas_maquina_m_a_ejecutadas", label: "Horas Máquina M.A - EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "dias_volqueta_m_a_ejecutadas", label: "Días Volqueta M.A -EJECUTADAS", type: "number", excelWidth: 28 },
  { name: "num_modificacion", label: "Num_modificación", type: "text", excelWidth: 18 },
  { name: "tipo_de_modificacion", label: "Tipo de modificación", type: "text", excelWidth: 18 },
  { name: "modificacion", label: "Modificación", type: "text", excelWidth: 18 },
  { name: "horas_maquina", label: "Horas Máquina", type: "number", excelWidth: 18 },
  { name: "dias_volqueta", label: "Días Volqueta", type: "number", excelWidth: 18 },
  { name: "sin_info", label: "sin info", type: "text", excelWidth: 18 },
  { name: "valor_parcial_1", label: "Valor parcial 1", type: "number", excelWidth: 18 },
  { name: "valor_parcial_2", label: "Valor parcial 2", type: "number", excelWidth: 18 },
  { name: "valor_parcial_3", label: "Valor parcial 3", type: "number", excelWidth: 18 },
  { name: "observaciones", label: "obs", type: "textarea", excelWidth: 18 },
  { name: "horas", label: "horas", type: "number", excelWidth: 18 },
  { name: "verif", label: "verif", type: "text", excelWidth: 18 },
  { name: "proceso", label: "Proceso", type: "text", excelWidth: 18 },
  { name: "comentario", label: "comentario", type: "textarea", excelWidth: 18 },
  { name: "valor_op_parcial", label: "Valor OP - parcial", type: "number", excelWidth: 18 },
  { name: "ano", label: "Año", type: "text", excelWidth: 18 },
  { name: "n_contrato", label: "N° Contrato", type: "text", excelWidth: 18 },
  { name: "sd_solicitud_de_desembolso", label: "SD (Solicitud de desembolso)", type: "text", excelWidth: 28 },
  { name: "valor_pagado_sin_impuestos", label: "Valor Pagado sin impuestos", type: "number", excelWidth: 28 },
  { name: "valor_pagado_total_con_impuestos", label: "Valor Pagado Total con impuestos", type: "number", excelWidth: 28 },
  { name: "saldo_a_liberar", label: "Saldo a liberar", type: "text", excelWidth: 18 },
  { name: "saldo_por_liberar", label: "Saldo Por Liberar", type: "text", excelWidth: 18 },
  { name: "comentario_depuracion", label: "comentario depuracion", type: "textarea", excelWidth: 18 },
  { name: "odern_3", label: "ODERN 3", type: "text", excelWidth: 18 },
];

export const SCHEMA_VERSION = 3;
