/**
 * Campos generados desde fuentes reales (maqueta / bitácora / ArcGIS).
 * NO editar a mano — regenerar: node scripts/generate-theme-fields.cjs
 * Fuente: OBRAS DE EMERGENCIA+O.P. OBRAS DE EMERGENCIA
 * schemaVersion 3: capas + clave_seguimiento para cruces y seguimiento.
 */
import type { FormField } from "../shared";

export const SOURCE_FIELDS: FormField[] = [
  { name: "tipo_registro", label: "Tipo de registro", type: "select", required: true, options: ["Contrato de obra","Orden de proveeduría"], excelWidth: 24 },
  { name: "capa", label: "Capa (Maqueta / Bitácora / …)", type: "select", required: true, options: ["Contrato de obra","Orden de proveeduría"], excelWidth: 22 },
  { name: "clave_seguimiento", label: "Clave de seguimiento (Orden de proveeduría / Contrato)", type: "text", excelWidth: 28 },
  { name: "orden_de_proveeduria", label: "Orden de proveeduría / Contrato", type: "text", excelWidth: 22 },
  { name: "id", label: "ID", type: "text", excelWidth: 18 },
  { name: "departamento", label: "DEPARTAMENTO", type: "text", excelWidth: 18 },
  { name: "municipio", label: "MUNICIPIO", type: "text", excelWidth: 18 },
  { name: "contrato_de_obra", label: "CONTRATO DE OBRA", type: "text", excelWidth: 18 },
  { name: "divipola", label: "DIVIPOLA", type: "text", excelWidth: 18 },
  { name: "lugar", label: "LUGAR", type: "text", excelWidth: 18 },
  { name: "obra_realizada", label: "OBRA REALIZADA", type: "text", excelWidth: 18 },
  { name: "objeto_del_contrato", label: "OBJETO DEL CONTRATO", type: "textarea", excelWidth: 18 },
  { name: "latitud", label: "LATITUD", type: "number", excelWidth: 18 },
  { name: "longitud", label: "LONGITUD", type: "number", excelWidth: 18 },
  { name: "contratista", label: "CONTRATISTA", type: "text", excelWidth: 18 },
  { name: "estado", label: "ESTADO ACTUAL DE LA OBRA", type: "text", excelWidth: 18 },
  { name: "estado_de_pago", label: "ESTADO DE PAGO", type: "text", excelWidth: 18 },
  { name: "valor", label: "VALOR CONTRATO", type: "number", excelWidth: 18 },
  { name: "plazo", label: "PLAZO", type: "text", excelWidth: 18 },
  { name: "fecha", label: "FECHA INICIO", type: "date", excelWidth: 18 },
  { name: "fecha_finalizacion_uno", label: "FECHA FINALIZACION UNO", type: "date", excelWidth: 18 },
  { name: "no_cdp", label: "CDP", type: "text", excelWidth: 18 },
  { name: "no_rc", label: "RC", type: "text", excelWidth: 18 },
  { name: "anticipo", label: "ANTICIPO", type: "text", excelWidth: 18 },
  { name: "porcentaje_anticipo", label: "PORCENTAJE ANTICIPO", type: "number", excelWidth: 18 },
  { name: "valor_anticipo", label: "VALOR ANTICIPO", type: "number", excelWidth: 18 },
  { name: "modificacion_contractual", label: "MODIFICACION CONTRACTUAL", type: "text", excelWidth: 18 },
  { name: "otrosi_uno", label: "OTROSI UNO", type: "text", excelWidth: 18 },
  { name: "tipo_otrosi_uno", label: "TIPO OTROSI UNO", type: "text", excelWidth: 18 },
  { name: "tiempo_prorroga_uno", label: "TIEMPO PRORROGA UNO", type: "text", excelWidth: 18 },
  { name: "adicion_uno", label: "ADICION UNO", type: "text", excelWidth: 18 },
  { name: "cdp_prorroga_uno", label: "CDP PRORROGA UNO", type: "text", excelWidth: 18 },
  { name: "rc_prorroga_uno", label: "RC PRORROGA UNO", type: "text", excelWidth: 18 },
  { name: "fecha_finalizacion_dos", label: "FECHA FINALIZACION DOS", type: "date", excelWidth: 18 },
  { name: "justificacion_modificacion_contractual_uno", label: "JUSTIFICACION MODIFICACION CONTRACTUAL UNO", type: "textarea", excelWidth: 28 },
  { name: "otrosi_dos", label: "OTROSI DOS", type: "text", excelWidth: 18 },
  { name: "tipo_otrosi_dos", label: "TIPO OTROSI DOS", type: "text", excelWidth: 18 },
  { name: "tiempo_prorroga_dos", label: "TIEMPO PRORROGA DOS", type: "text", excelWidth: 18 },
  { name: "adicion_dos", label: "ADICION DOS", type: "text", excelWidth: 18 },
  { name: "cdp_mod_contract", label: "CDP MOD CONTRACT", type: "text", excelWidth: 18 },
  { name: "rc_mod_contrac", label: "RC MOD CONTRAC", type: "text", excelWidth: 18 },
  { name: "fecha_finalizacion_tres", label: "FECHA FINALIZACION TRES", type: "date", excelWidth: 18 },
  { name: "justificacion_mod_cont_dos", label: "JUSTIFICACION MOD CONT DOS", type: "textarea", excelWidth: 28 },
  { name: "otrosi_tres", label: "OTROSI TRES", type: "text", excelWidth: 18 },
  { name: "tipo_otrosi_tres", label: "TIPO OTROSI TRES", type: "text", excelWidth: 18 },
  { name: "tiempo_prorroga_tres", label: "TIEMPO PRORROGA TRES", type: "text", excelWidth: 18 },
  { name: "adicion_tres", label: "ADICION TRES", type: "text", excelWidth: 18 },
  { name: "fecha_finalizacion_cuatro", label: "FECHA FINALIZACION CUATRO", type: "date", excelWidth: 28 },
  { name: "justificacion_mod_cont_tres", label: "JUSTIFICACION MOD CONT TRES", type: "textarea", excelWidth: 28 },
  { name: "avance_fisico_ejecutado", label: "AVANCE FISICO EJECUTADO", type: "number", excelWidth: 18 },
  { name: "avance_financiero_ejecutado", label: "AVANCE FINANCIERO EJECUTADO", type: "number", excelWidth: 28 },
  { name: "avance_fisico_programado", label: "AVANCE FISICO PROGRAMADO", type: "number", excelWidth: 18 },
  { name: "cuentas_de_cobro_tramitadas", label: "CUENTAS DE COBRO TRAMITADAS", type: "text", excelWidth: 28 },
  { name: "observaciones", label: "MINUTA Y OBSERVACIONES", type: "textarea", excelWidth: 18 },
  { name: "contrato_de_interventoria", label: "CONTRATO DE INTERVENTORIA", type: "text", excelWidth: 28 },
  { name: "objeto_contrato_de_interventoria", label: "OBJETO CONTRATO DE INTERVENTORIA", type: "textarea", excelWidth: 28 },
  { name: "contratista_cont_interv", label: "CONTRATISTA CONT INTERV", type: "text", excelWidth: 18 },
  { name: "supervisor_conti_nterv", label: "SUPERVISOR CONTI NTERV", type: "text", excelWidth: 18 },
  { name: "valor_cont_interv", label: "VALOR CONT INTERV", type: "number", excelWidth: 18 },
  { name: "plazo_cont_interv", label: "PLAZO CONT INTERV", type: "text", excelWidth: 18 },
  { name: "acta_de_inicio_fecha_inicial", label: "ACTA DE INICIO FECHA INICIAL", type: "date", excelWidth: 28 },
  { name: "acta_de_inicio_fecha_final", label: "ACTA DE INICIO FECHA FINAL", type: "date", excelWidth: 28 },
  { name: "cdp_cont_interv", label: "CDP CONT INTERV", type: "text", excelWidth: 18 },
  { name: "rc_cont_interv", label: "RC CONT INTERV", type: "text", excelWidth: 18 },
  { name: "modificacion_contrac_cont_interv", label: "MODIFICACION CONTRAC CONT INTERV", type: "text", excelWidth: 28 },
  { name: "otrosi_uno_cont_interv", label: "OTROSI UNO CONT INTERV", type: "text", excelWidth: 18 },
  { name: "tipo_otrosi_cont_inter", label: "TIPO OTROSI CONT INTER", type: "text", excelWidth: 18 },
  { name: "tiempo_prorroga_cont_interv", label: "TIEMPO PRORROGA CONT INTERV", type: "text", excelWidth: 28 },
  { name: "adicion_prorroga_cont_interv", label: "ADICION PRORROGA CONT INTERV", type: "text", excelWidth: 28 },
  { name: "cdp_prorroga_cont_interv", label: "CDP PRORROGA CONT INTERV", type: "text", excelWidth: 18 },
  { name: "rc_prorroga_cont_interv", label: "RC PRORROGA CONT INTERV", type: "text", excelWidth: 18 },
  { name: "fecha_de_finalizacion_cont_interv", label: "FECHA DE FINALIZACION CONT INTERV", type: "date", excelWidth: 28 },
  { name: "justificacion_mod_contractual_cont_int", label: "JUSTIFICACION MOD CONTRACTUAL CONT INT", type: "textarea", excelWidth: 28 },
  { name: "otrosi_interv_dos", label: "OTROSI INTERV DOS", type: "text", excelWidth: 18 },
  { name: "tipo_otrosi_interv_dos", label: "TIPO OTROSI INTERV DOS", type: "text", excelWidth: 18 },
  { name: "tiempo_interv_dos", label: "TIEMPO INTERV DOS", type: "text", excelWidth: 18 },
  { name: "adicion_interv_dos", label: "ADICION INTERV DOS", type: "text", excelWidth: 18 },
  { name: "cdp_mod_contract_interv", label: "CDP MOD CONTRACT INTERV", type: "text", excelWidth: 18 },
  { name: "rc_mod_contrac_interv", label: "RC MOD CONTRAC INTERV", type: "text", excelWidth: 18 },
  { name: "fecha_finalizacion_interv_tres", label: "FECHA FINALIZACION INTERV TRES", type: "date", excelWidth: 28 },
  { name: "justificacion_mod_cont_interv_dos", label: "JUSTIFICACION MOD CONT INTERV DOS", type: "textarea", excelWidth: 28 },
  { name: "avance_fisico_ejecutado_cont_interv", label: "AVANCE FISICO EJECUTADO CONT INTERV", type: "number", excelWidth: 28 },
  { name: "avance_financiero_ejecutado_cont_interv", label: "% AVANCE FINANCIERO EJECUTADO CONT INTERV", type: "number", excelWidth: 28 },
  { name: "avance_fisico_programado_cont_interv", label: "AVANCE FISICO PROGRAMADO CONT INTERV", type: "number", excelWidth: 28 },
  { name: "cuenta_de_cobro_tramitadas_cont_interv", label: "CUENTA DE COBRO TRAMITADAS CONT INTERV", type: "text", excelWidth: 28 },
  { name: "minuta_y_obs_cont_interv", label: "MINUTA Y OBS CONT INTERV", type: "textarea", excelWidth: 18 },
  { name: "tipo_de_contrato", label: "TIPO DE CONTRATO", type: "text", excelWidth: 18 },
  { name: "horas_maquina", label: "HORAS MAQUINA", type: "number", excelWidth: 18 },
  { name: "dias_volqueta", label: "DIAS VOLQUETA", type: "number", excelWidth: 18 },
  { name: "proveedor", label: "PROVEEDOR", type: "text", excelWidth: 18 },
  { name: "nit", label: "NIT", type: "text", excelWidth: 18 },
  { name: "representante_legal", label: "REPRESENTANTE LEGAL", type: "text", excelWidth: 18 },
  { name: "cc_representante_legal", label: "CC REPRESENTANTE LEGAL", type: "text", excelWidth: 18 },
  { name: "telefono_contratista", label: "TELEFONO CONTRATISTA", type: "text", excelWidth: 18 },
  { name: "correo_contratista", label: "CORREO CONTRATISTA", type: "text", excelWidth: 18 },
  { name: "fecha_orden", label: "FECHA ORDEN", type: "date", excelWidth: 18 },
  { name: "fecha_aceptacion", label: "FECHA ACEPTACION", type: "date", excelWidth: 18 },
  { name: "fecha_de_activacion", label: "FECHA DE ACTIVACION", type: "date", excelWidth: 18 },
  { name: "fecha_finalizacion", label: "FECHA FINALIZACION", type: "date", excelWidth: 18 },
  { name: "alcance_uno", label: "ALCANCE UNO", type: "text", excelWidth: 18 },
  { name: "tipo_alcance_uno", label: "TIPO ALCANCE UNO", type: "text", excelWidth: 18 },
  { name: "alcance_dos", label: "ALCANCE DOS", type: "text", excelWidth: 18 },
  { name: "tipo_alcance_dos", label: "TIPO ALCANCE DOS", type: "text", excelWidth: 18 },
  { name: "tiempo_de_prorroga_dos", label: "TIEMPO DE PRORROGA DOS", type: "text", excelWidth: 18 },
  { name: "cdp_prorroga_dos", label: "CDP PRORROGA DOS", type: "text", excelWidth: 18 },
  { name: "rc_prorroga_dos", label: "RC PRORROGA DOS", type: "text", excelWidth: 18 },
  { name: "justificacion_modificacion_contractual_dos", label: "JUSTIFICACION MODIFICACION CONTRACTUAL DOS", type: "textarea", excelWidth: 28 },
  { name: "alcance_tres", label: "ALCANCE TRES", type: "text", excelWidth: 18 },
  { name: "tipo_alcance_tres", label: "TIPO ALCANCE TRES", type: "text", excelWidth: 18 },
  { name: "tiempo_de_prorroga_tres", label: "TIEMPO DE PRORROGA TRES", type: "text", excelWidth: 18 },
  { name: "cdp_prorroga_tres", label: "CDP PRORROGA TRES", type: "text", excelWidth: 18 },
  { name: "rc_prorroga_tres", label: "RC PRORROGA TRES", type: "text", excelWidth: 18 },
  { name: "justificacion_modificacion_contractual_tres", label: "JUSTIFICACION MODIFICACION CONTRACTUAL TRES", type: "textarea", excelWidth: 28 },
  { name: "alcance_cuatro", label: "ALCANCE CUATRO", type: "text", excelWidth: 18 },
  { name: "tipo_alcance_cuatro", label: "TIPO ALCANCE CUATRO", type: "text", excelWidth: 18 },
  { name: "tiempo_de_prorroga_cuatro", label: "TIEMPO DE PRORROGA CUATRO", type: "text", excelWidth: 28 },
  { name: "adicion_cuatro", label: "ADICION CUATRO", type: "text", excelWidth: 18 },
  { name: "cdp_prorroga_cuatro", label: "CDP PRORROGA CUATRO", type: "text", excelWidth: 18 },
  { name: "rc_prorroga_cuatro", label: "RC PRORROGA CUATRO", type: "text", excelWidth: 18 },
  { name: "fecha_finalizacion_cinco", label: "FECHA FINALIZACION CINCO", type: "date", excelWidth: 18 },
  { name: "porcentaje_avance_financiero_ejecutado", label: "PORCENTAJE AVANCE FINANCIERO EJECUTADO", type: "number", excelWidth: 28 },
  { name: "porcentaje_avance_fisico_ejecutado", label: "PORCENTAJE AVANCE FISICO EJECUTADO", type: "number", excelWidth: 28 },
  { name: "porcentaje_avance_fisico_programado", label: "PORCENTAJE AVANCE FISICO PROGRAMADO", type: "number", excelWidth: 28 },
];

export const SCHEMA_VERSION = 3;
