/**
 * Campos generados desde fuentes reales (maqueta / bitácora / ArcGIS).
 * NO editar a mano — regenerar: node scripts/generate-theme-fields.cjs
 * Fuente: DETALLE+CONVENIOS+BITACORA+ENTREGA
 * schemaVersion 3: capas + clave_seguimiento para cruces y seguimiento.
 */
import type { FormField } from "../shared";

export const SOURCE_FIELDS: FormField[] = [
  { name: "tipo_registro", label: "Tipo de registro", type: "select", required: true, options: ["Maqueta / inventario","Convenio o proceso","Bitácora convenio","Entrega a beneficiario"], excelWidth: 24 },
  { name: "capa", label: "Capa (Maqueta / Bitácora / …)", type: "select", required: true, options: ["Maqueta / inventario","Convenio o proceso","Bitácora convenio","Entrega a beneficiario"], excelWidth: 22 },
  { name: "clave_seguimiento", label: "Clave de seguimiento (Serial / Nº máquina / Nº convenio)", type: "text", excelWidth: 28 },
  { name: "serial", label: "Serial / Nº máquina / Nº convenio", type: "text", excelWidth: 22 },
  { name: "estado", label: "Estado", type: "text", excelWidth: 16 },
  { name: "municipio", label: "Municipio (DIVIPOLA)", type: "text", excelWidth: 16 },
  { name: "no_maquina", label: "No. Maquina", type: "text", excelWidth: 18 },
  { name: "referencia", label: "REFERENCIA", type: "text", excelWidth: 18 },
  { name: "nit", label: "NIT", type: "text", excelWidth: 18 },
  { name: "clasificacion", label: "CLASIFICACION", type: "text", excelWidth: 18 },
  { name: "empresa", label: "EMPRESA", type: "text", excelWidth: 18 },
  { name: "entidad_receptora", label: "ENTIDAD RECEPTORA", type: "text", excelWidth: 18 },
  { name: "tipo_maquinaria", label: "TIPO MAQUINARIA", type: "text", excelWidth: 18 },
  { name: "departamento", label: "DEPARTAMENTO", type: "text", excelWidth: 18 },
  { name: "valor", label: "VALOR UNITARIO", type: "number", excelWidth: 18 },
  { name: "n_motor", label: "N. MOTOR", type: "text", excelWidth: 18 },
  { name: "fecha", label: "FECHA DE RECIBO", type: "date", excelWidth: 18 },
  { name: "fecha_entrega_o_recibo", label: "FECHA ENTREGA O RECIBO", type: "date", excelWidth: 18 },
  { name: "ano_modelo", label: "AÑO MODELO", type: "number", excelWidth: 18 },
  { name: "placa", label: "PLACAS", type: "text", excelWidth: 18 },
  { name: "chasis_camabaja", label: "CHASIS CAMABAJA", type: "text", excelWidth: 18 },
  { name: "placa_camabaja", label: "PLACA CAMABAJA", type: "text", excelWidth: 18 },
  { name: "linea", label: "LINEA", type: "text", excelWidth: 18 },
  { name: "modelo_y_o_referencia", label: "MODELO Y/O REFERENCIA", type: "text", excelWidth: 18 },
  { name: "modalidad", label: "MODALIDAD", type: "text", excelWidth: 18 },
  { name: "no_orden_de_compra", label: "NO ORDEN DE COMPRA", type: "text", excelWidth: 18 },
  { name: "no_convenio", label: "CONTRATO DE ADQUISICION O CONVENIO", type: "text", excelWidth: 28 },
  { name: "registrada_ante_el_runt", label: "REGISTRADA ANTE EL RUNT", type: "text", excelWidth: 18 },
  { name: "observaciones", label: "OBSERVACION", type: "textarea", excelWidth: 18 },
  { name: "encargado", label: "ENCARGADO", type: "text", excelWidth: 18 },
  { name: "cargo_encargad", label: "CARGO ENCARGAD", type: "text", excelWidth: 18 },
  { name: "objeto", label: "OBJETO", type: "textarea", excelWidth: 18 },
  { name: "cantidad_maquinaria_espectativa", label: "CANTIDAD MAQUINARIA ESPECTATIVA", type: "number", excelWidth: 28 },
  { name: "cantidad_maquinaria_entregada", label: "CANTIDAD MAQUINARIA ENTREGADA", type: "number", excelWidth: 28 },
  { name: "tiempo_de_ejecucion", label: "TIEMPO DE EJECUCION", type: "text", excelWidth: 18 },
  { name: "fecha_acta_de_inicio", label: "Fecha Acta de Inicio", type: "date", excelWidth: 18 },
  { name: "no_cdp", label: "CDP", type: "text", excelWidth: 18 },
  { name: "fecha_cdp", label: "FECHA CDP", type: "date", excelWidth: 18 },
  { name: "no_rc", label: "RC", type: "text", excelWidth: 18 },
  { name: "fecha_de_rc", label: "FECHA DE RC", type: "date", excelWidth: 18 },
  { name: "valor_sin_iva", label: "VALOR SIN IVA", type: "number", excelWidth: 18 },
  { name: "valor_aporte_municipio", label: "VALOR APORTE MUNICIPIO", type: "number", excelWidth: 18 },
  { name: "valor_aporte_ungrd", label: "VALOR APORTE UNGRD", type: "number", excelWidth: 18 },
  { name: "responsable_juridico", label: "RESPONSABLE JURIDICO", type: "text", excelWidth: 18 },
  { name: "responsable_financiero", label: "RESPONSABLE FINANCIERO", type: "text", excelWidth: 18 },
  { name: "responsable_tecnico", label: "RESPONSABLE TECNICO", type: "text", excelWidth: 18 },
  { name: "comentario", label: "COMENTARIO", type: "textarea", excelWidth: 18 },
  { name: "tipo", label: "TIPO", type: "text", excelWidth: 18 },
  { name: "comandante_o_rep_legal", label: "COMANDANTE O REP LEGAL", type: "text", excelWidth: 18 },
  { name: "cedula", label: "CEDULA", type: "text", excelWidth: 18 },
  { name: "celular", label: "CELULAR", type: "text", excelWidth: 18 },
  { name: "correo_electronico", label: "CORREO ELECTRONICO", type: "text", excelWidth: 18 },
  { name: "resolucion_de_nombramiento_comandante", label: "RESOLUCIÓN DE NOMBRAMIENTO COMANDANTE", type: "text", excelWidth: 28 },
  { name: "acta_perfeccionada", label: "ACTA PERFECCIONADA", type: "text", excelWidth: 18 },
  { name: "acta_en_fisico", label: "ACTA EN FISICO", type: "text", excelWidth: 18 },
  { name: "poliza_inicial_todo_riesgo", label: "POLIZA  INICIAL TODO RIESGO", type: "text", excelWidth: 28 },
  { name: "fecha_envio_acta_perfeccionada_cuerpo_de_bomberos", label: "FECHA ENVIO ACTA PERFECCIONADA CUERPO DE BOMBEROS", type: "date", excelWidth: 28 },
  { name: "inicio_vigencia_poliza_tr", label: "INICIO VIGENCIA POLIZA TR", type: "text", excelWidth: 28 },
  { name: "fin_vigencia_poliza_tr", label: "FIN VIGENCIA POLIZA TR", type: "text", excelWidth: 18 },
  { name: "dias", label: "DIAS", type: "number", excelWidth: 18 },
  { name: "alerta_poliza_tr", label: "ALERTA POLIZA TR", type: "text", excelWidth: 18 },
  { name: "fecha_inicio_soat", label: "FECHA INICIO SOAT", type: "date", excelWidth: 18 },
  { name: "fcha_terminacion_soat", label: "FCHA TERMINACION SOAT", type: "text", excelWidth: 18 },
  { name: "alerta_soat", label: "ALERTA SOAT", type: "text", excelWidth: 18 },
  { name: "fecha_de_envio_1_oficio_ungrd_al_cuerpo_de_bomberos", label: "Fecha de envio 1º oficio UNGRD  al cuerpo de bomberos", type: "date", excelWidth: 28 },
  { name: "1_informe_2024", label: "1º informe 2024", type: "text", excelWidth: 18 },
  { name: "2_informe_2024", label: "2º informe 2024", type: "text", excelWidth: 18 },
  { name: "soat_2025", label: "SOAT 2025", type: "text", excelWidth: 18 },
  { name: "poliza_todo_riesgo", label: "POLIZA TODO RIESGO", type: "text", excelWidth: 18 },
  { name: "bitacora_de_mantenimiento", label: "BITACORA DE MANTENIMIENTO", type: "text", excelWidth: 28 },
  { name: "plan_de_accion_2024", label: "PLAN DE ACCION 2024", type: "text", excelWidth: 18 },
  { name: "fotografias_equipo", label: "FOTOGRAFIAS EQUIPO", type: "text", excelWidth: 18 },
];

export const SCHEMA_VERSION = 3;
