import type { FormField } from "../shared";

export const SCHEMA_VERSION = 5;

/** Campos de la pestaña SMD del reporte Fidusap (más GRUPO inferido). */
export const SOURCE_FIELDS: FormField[] = [
  { name: "departamento", label: "Departamento", type: "text", excelWidth: 18 },
  { name: "municipio", label: "Municipio", type: "text", excelWidth: 18 },
  { name: "no_cdp", label: "No. CDP", type: "text", required: true, excelWidth: 14 },
  { name: "valor_cdp", label: "Valor CDP", type: "number", excelWidth: 16 },
  { name: "radicado_cdp", label: "Radicado CDP", type: "text", excelWidth: 14 },
  { name: "solicitante", label: "Solicitante", type: "text", excelWidth: 28 },
  { name: "area_ejecutora", label: "Área ejecutora", type: "text", excelWidth: 12 },
  { name: "grupo", label: "Grupo", type: "text", excelWidth: 18 },
  { name: "descripcion", label: "Descripción", type: "textarea", excelWidth: 40 },
  { name: "fecha_cdp", label: "Fecha CDP", type: "date", excelWidth: 14 },
  { name: "resolucion", label: "Resolución", type: "text", excelWidth: 16 },
  { name: "alias", label: "Alias", type: "text", excelWidth: 28 },
  { name: "fuente", label: "Fuente", type: "text", excelWidth: 28 },
  { name: "linea", label: "Línea", type: "text", excelWidth: 18 },
  { name: "nota", label: "Nota", type: "textarea", excelWidth: 22 },
  { name: "rubro", label: "Rubro", type: "text", excelWidth: 28 },
  { name: "nacional_regional", label: "Nacional / regional", type: "text", excelWidth: 18 },
  { name: "identificacion", label: "Identificación", type: "text", excelWidth: 16 },
  { name: "nombre", label: "Nombre", type: "text", excelWidth: 22 },
  { name: "no_rc", label: "No. RC", type: "text", excelWidth: 14 },
  { name: "fecha_rc", label: "Fecha RC", type: "date", excelWidth: 14 },
  { name: "estado", label: "Estado", type: "text", excelWidth: 14 },
  { name: "tipo", label: "Tipo", type: "text", excelWidth: 22 },
  { name: "valor_rc", label: "Valor RC", type: "number", excelWidth: 16 },
  { name: "contrato", label: "Contrato", type: "text", excelWidth: 18 },
  { name: "area_solicitante", label: "Área solicitante", type: "text", excelWidth: 28 },
  { name: "radicado_rc", label: "Radicado RC", type: "text", excelWidth: 14 },
  { name: "fecha_inicial", label: "Fecha inicial", type: "date", excelWidth: 14 },
  { name: "fecha_final", label: "Fecha final", type: "date", excelWidth: 14 },
  { name: "valor_pagado", label: "Valor pagado", type: "number", excelWidth: 16 },
  { name: "valor_por_pagar", label: "Valor por pagar", type: "number", excelWidth: 16 },
  { name: "nombre_firma", label: "Nombre firma", type: "text", excelWidth: 20 },
  { name: "cargo_firma", label: "Cargo firma", type: "text", excelWidth: 18 },
  { name: "usuario", label: "Usuario", type: "text", excelWidth: 14 },
  { name: "clave_seguimiento", label: "Clave de seguimiento", type: "text", excelWidth: 16 },
  { name: "tipo_registro", label: "Grupo", type: "text", excelWidth: 18 },
  { name: "capa", label: "Capa", type: "text", excelWidth: 18 },
  { name: "fecha", label: "Fecha", type: "date", excelWidth: 14 },
  { name: "valor", label: "Valor CDP", type: "number", excelWidth: 16 },
  { name: "observaciones", label: "Observaciones", type: "textarea", excelWidth: 24 },
];
